name: github_actions_gcp
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - scikit-learn==1.0.*
  - numpy<2
  - joblib
  - pytest
  - google-cloud-sdk
  - pip:
    - google-cloud-aiplatform[prediction,autologging]