name: Train Model GCP

on:
  push:
    branches:
      - main
    paths:
      - 'trainer/task.py'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
        
      - name: Install dependencies
        run: |
          pip install setuptools --upgrade
          echo "Listing installed packages"
          pip list
          echo "Requirements file contents"
          cat trainer/requirements.txt
          echo "Installing dependencies"
          pip install -r trainer/requirements.txt

      - name: Testing
        run: pytest

  train:
    runs-on: ubuntu-22.04
    needs: test
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install setuptools --upgrade
        pip install -r trainer/requirements.txt

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        project_id: ${{ secrets.PROJECT_ID }}
        workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          
    - name: Training
      run: python train.py
      env:
        VERTEX_SA: ${{ secrets.VERTEX_SA }}
        PROJECT_ID: ${{ secrets.PROJECT_ID }}
        LOCATION: ${{ secrets.LOCATION }}
        BUCKET_NAME: ${{ secrets.BUCKET_NAME }}

    - name: Deploying
      run: python deploy.py
      env:
        VERTEX_SA: ${{ secrets.VERTEX_SA }}
        PROJECT_ID: ${{ secrets.PROJECT_ID }}
        LOCATION: ${{ secrets.LOCATION }}
        BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
